version: '3'
services:
  expo:
    build: .
    command: ["sh", "-c", "sleep 5 && sync && yarn start"]

    volumes:
      - app-sync:/app:nocopy
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
      - "8081:8081"
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
volumes:
  app-sync:
    external: true
  node_modules: