name: Push to Central Repository

on:
  push:
    branches:
      - dev

jobs:
  sync-to-central-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Setup Git User
        run: |
          git config --global user.name "Bartoszkk"
          git config --global user.email "Bartosz.michalak@epitech.eu"

      - name: Sync to Central Repository
        env:
          CENTRAL_REPO: 'git@github.com:EpitechPromo2026/B-DEV-500-TLS-5-2-area-alexandre.lagasse.git'
        run: |
          # Adding central repository
          git remote add central "${CENTRAL_REPO}"
          git fetch central
          
          # Create a new local branch that tracks central/main
          git checkout -b local-main central/main
          
          # Check if AREA-MOBILE directory exists, remove if it does
          if [ -d "AREA-MOBILE/" ]; then
            git rm AREA-MOBILE/
            git add AREA-MOBILE
            git commit -m "Remove existing AREA-MOBILE directory"
          else
            mkdir AREA-MOBILE
            git add AREA-MOBILE
            git commit -m "Create AREA-MOBILE directory"
          fi

          # Copy the repository contents into AREA-MOBILE, excluding .git and .github
          rsync -av --exclude='.git' --exclude='.github' ./ AREA-MOBILE/

          # Commit and push the changes
          git add AREA-MOBILE
          git commit -m "Update AREA-MOBILE content"
          git push central local-main:main
